### ISSUE TITLE
Traffic not routed to new host of IP address 

### ISSUE THREAD

**Issue by MatthewKohner** [cybertec-postgresql/vip-manager#12] opened 2018-09-24 14:49 UTC
When failing over to a new Postgres host, the IP is assigned to the new host and removed from the old host, but traffic fails to be routed to the new host until roughly 15 minutes later.

Workaround is to do a ```arping -c 4 -A -I <interface> <ip address> ``` 
Ubuntu 18.04

**Comment by cultcom** [comment] 2019-02-04 15:33
We are seeing the same problem. I could find this in the logs:

Jan 22 14:29:25 pg-node02 bash[699]: 2019/01/22 14:29:25 IP address x.x.x.2/24 state is false, desired true
Jan 22 14:29:25 pg-node02 bash[699]: 2019/01/22 14:29:25 Configuring address x.x.x.2/24 on ens192
Jan 22 14:29:25 pg-node02 bash[699]: 2019/01/22 14:29:25 Cannot send gratuitous arp message: network is down

I cannot tell why this happens as the interface is actually up.

**Comment by MatthewKohner** [comment] 2019-02-12 14:54
@martinseener @cultcom I ended up putting in a hack to call arping repeatedly like OpenNebula does when an IP address is migrated. See https://github.com/OpenNebula/one/blob/2ff0324bb224dd73d246b864bd0cd9eea115e998/share/hooks/raft/vip.sh#L30 From what I have gathered the behavior is dependent on the particulars of the network infrastructure. Not all OSes and routers behave well, but this solution works for us.

**Comment by ich199** [comment] 2020-02-17 13:14
We are still seeing this issue with the version 0.6 release, in our environment. The issue appears to be caused by https://github.com/cybertec-postgresql/vip-manager/blob/master/basicConfigurer.go#L69 where the destination IP is being set to the broadcast address rather than being set to the same as the source IP as described in https://wiki.wireshark.org/Gratuitous_ARP

Updating the code to use `c.vip`, rather than `net.IPv4bcast` as the destination IP resolves this issue for us.

**Comment by markwort** [comment] 2020-03-03 18:17
Hey, thanks for spotting this!
The original author of this portion of the code must have not read the RFC (who can blame them..) And presumably some networks filter out gratuitous arp packages that are not entirely RFC conforming.

**Comment by markwort** [comment] 2020-04-03 17:17
hey guys, @ich199, @cultcom  @MatthewKohner and @martinseener , I've created a patch (after reading up on how this gARP stuff actually needs to be handled).

I'd be glad if you could test the changes that I made in the pull request to see if they now work in your specific networking environments.
This is difficult to test as-is, and I certainly can't test this with specifc firewalls and networking hardware...

For simple testing, I suggest that you create a local etcd server, create the key upon which vip-manager would trigger and start one or two vip-managers locally.
When running two locally, you need to give each of them a different VIP-address, as the node that is not allowed to have the VIP will see that the VIP is actually registered on the local interface (unbeknownst to it, by the other vip-manager) and think this is a mistake and will remove it everytime it comes around and sees this. Then the other vip-manager will register again and so on...

run an etcd instance:
```
podman run -d --name etcd -p 2379:2379 -e "ETCD_ENABLE_V2=true" -e "ALLOW_NONE_AUTHENTICATION=yes" bitnami/etcd
```

start two vip-managers (best in two windows, or pipe the output to different logfiles, so you can see what's going on):
```
sudo ./vip-manager -endpoint http://localhost:2379 -host pgcluster_member1 -key /service/pgcluster/leader -ip 192.168.178.111 -mask 24 -iface enp33s0

sudo ./vip-manager -endpoint http://localhost:2379 -host pgcluster_member2 -key /service/pgcluster/leader -ip 192.168.178.112 -mask 24 -iface enp33s0
```

simulate patroni leader:
```curl -s -XPUT http://127.0.0.1:2379/v2/keys/service/pgcluster/leader -d value=pgcluster_member1 | jq
```

simulate patroni leader change:
```
curl -s -XPUT http://127.0.0.1:2379/v2/keys/service/pgcluster/leader -d value=pgcluster_member2 | jq
```

simulate loss of leader:
```
curl -s -XDELETE http://127.0.0.1:2379/v2/keys/service/pgcluster/leader | jq
```

Obviuosly, the mere note "successfully sent gARP reply/request" does not indicate any success as perceived by other machines in the network.
I've found this difficult to test, as my linux machines will not accept gARP requests/replies, regardless of how I configure the kernel, so I cannot gain anything useful from the ARP tables there.
Maybe one of you can take a look at your switches' ARP tables...


All the best
Julian

**Comment by ich199** [comment] 2020-04-24 11:05
Hi @markwort,

Sorry, I've only just been able to test the changes in #29, in our environment. Unfortunatly, it still didn't want to work, but I think this is due to the vendored version of `mdlayher/arp`.

With the version in the `/vendor` directory, there is an issue where the `arpClient.WriteTo` function ignores the `addr` parameter, and instead uses the target MAC address from the ARP packet. (https://github.com/cybertec-postgresql/vip-manager/blob/improve_gratuitous_arp/vendor/github.com/mdlayher/arp/client.go#L154)

So, in the case of #29 rather than using `ethernetBroadcast` (https://github.com/cybertec-postgresql/vip-manager/blob/improve_gratuitous_arp/basicConfigurer.go#L119 and https://github.com/cybertec-postgresql/vip-manager/blob/improve_gratuitous_arp/basicConfigurer.go#L126), it is instead using the local interface hardware address in the case of `gratuitousReplyPackage` (https://github.com/cybertec-postgresql/vip-manager/blob/improve_gratuitous_arp/basicConfigurer.go#L86) and a zero MAC address `00:00:00:00:00:00` in the case of `gratuitousRequestPackage` (https://github.com/cybertec-postgresql/vip-manager/blob/improve_gratuitous_arp/basicConfigurer.go#L110)


I've confirmed this behaviour with a packet caputre during a switchover:

Ethernet frame generated for `gratuitousReplyPackage`
```
Ethernet II, Src: Vmware_88:7e:6b (00:50:56:88:7e:6b), Dst: Vmware_88:7e:6b (00:50:56:88:7e:6b)
    Destination: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        Address: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        Address: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: ARP (0x0806)
    Padding: 000000000000000000000000000000000000
```

Ethernet frame generated for `gratuitousRequestPackage`
```Ethernet II, Src: Vmware_88:7e:6b (00:50:56:88:7e:6b), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
    Destination: 00:00:00_00:00:00 (00:00:00:00:00:00)
        Address: 00:00:00_00:00:00 (00:00:00:00:00:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        Address: Vmware_88:7e:6b (00:50:56:88:7e:6b)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: ARP (0x0806)
    Padding: 000000000000000000000000000000000000
```

It looks like this issue has been addressed in a newer version of `mdlayher/arp` (https://github.com/mdlayher/arp/pull/21).

I have confirmed that using this newer version of `mdlayher/arp` in #29 correctly uses `ethernetBroadcast` as the destination MAC and fixes this issue, in our environment.

**Closed** 2020-06-22 07:33 UTC
